# Setup a local statsd stack development
# docker-compose -f docker-compose.dev.yml up

graphite-statsd:
  image: hopsoft/graphite-statsd
  ports:
    - 8000:80
    - 2003-2004:2003-2004
    - 2023-2024:2023-2024
    - 8125:8125/udp
    - 8126:8126


# graphite starts at http://localhost:8000
