# Setup a local statsd stack development
# docker-compose -f docker-compose.dev.yml up

docker-statsd-influxdb-grafana:
  image: samuelebistoletti/docker-statsd-influxdb-grafana:latest
  ports:
    - "3003:3003"
    - "3004:8888"
    - "8086:8086"
    - "22022:22"
    - "8125:8125/udp"

# Services will starts at
# InfluxDB admin (Chronograf)
# http://localhost:3004/
# Grafana
# http://localhost:3003/